import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { IntroductionComponent } from './pages/introduction/introduction.component';
import { JudithComponent } from './pages/judith/judith.component';
import { ParisComponent } from './pages/paris/paris.component';
import { GreeceComponent } from './pages/greece/greece.component';
import { HerculesComponent } from './pages/hercules/hercules.component';
import { RomeComponent } from './pages/rome/rome.component';
import { MedievalComponent } from './pages/medieval/medieval.component';
import { RomanesqueComponent } from './pages/romanesque/romanesque.component';
import { GothicComponent } from './pages/gothic/gothic.component';
import { RenaissanceComponent } from './pages/renaissance/renaissance.component';
import { BaroqueComponent } from './pages/baroque/baroque.component';
import { NeoclassicismComponent } from './pages/neoclassicism/neoclassicism.component';
import { AboutComponent } from './pages/about/about.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'introduction', component: IntroductionComponent },
  { path: 'judith', component: JudithComponent },
  { path: 'paris', component: ParisComponent },
  { path: 'greece', component: GreeceComponent },
  { path: 'hercules', component: HerculesComponent },
  { path: 'rome', component: RomeComponent },
  { path: 'medieval', component: MedievalComponent },
  { path: 'romanesque', component: RomanesqueComponent },
  { path: 'gothic', component: GothicComponent },
  { path: 'renaissance', component: RenaissanceComponent },
  { path: 'baroque', component: BaroqueComponent },
  { path: 'neoclassicism', component: NeoclassicismComponent },
  { path: 'about', component: AboutComponent },
  { path: '**', redirectTo: '' }
];
